// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	models "example/web-service-gin/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockGoodsProvider is a mock of GoodsProvider interface.
type MockGoodsProvider struct {
	ctrl     *gomock.Controller
	recorder *MockGoodsProviderMockRecorder
}

// MockGoodsProviderMockRecorder is the mock recorder for MockGoodsProvider.
type MockGoodsProviderMockRecorder struct {
	mock *MockGoodsProvider
}

// NewMockGoodsProvider creates a new mock instance.
func NewMockGoodsProvider(ctrl *gomock.Controller) *MockGoodsProvider {
	mock := &MockGoodsProvider{ctrl: ctrl}
	mock.recorder = &MockGoodsProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGoodsProvider) EXPECT() *MockGoodsProviderMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockGoodsProvider) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockGoodsProviderMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockGoodsProvider)(nil).DeleteByID), ctx, id)
}

// GetGoodByID mocks base method.
func (m *MockGoodsProvider) GetGoodByID(ctx context.Context, id string) (*models.Footballstore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGoodByID", ctx, id)
	ret0, _ := ret[0].(*models.Footballstore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGoodByID indicates an expected call of GetGoodByID.
func (mr *MockGoodsProviderMockRecorder) GetGoodByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGoodByID", reflect.TypeOf((*MockGoodsProvider)(nil).GetGoodByID), ctx, id)
}

// InsertStore mocks base method.
func (m *MockGoodsProvider) InsertStore(ctx context.Context, newGood *models.Footballstore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertStore", ctx, newGood)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertStore indicates an expected call of InsertStore.
func (mr *MockGoodsProviderMockRecorder) InsertStore(ctx, newGood interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertStore", reflect.TypeOf((*MockGoodsProvider)(nil).InsertStore), ctx, newGood)
}

// ListStore mocks base method.
func (m *MockGoodsProvider) ListStore(ctx context.Context) ([]models.Footballstore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListStore", ctx)
	ret0, _ := ret[0].([]models.Footballstore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListStore indicates an expected call of ListStore.
func (mr *MockGoodsProviderMockRecorder) ListStore(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListStore", reflect.TypeOf((*MockGoodsProvider)(nil).ListStore), ctx)
}

// UpdateStore mocks base method.
func (m *MockGoodsProvider) UpdateStore(ctx context.Context, updatedGoods *models.Footballstore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStore", ctx, updatedGoods)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStore indicates an expected call of UpdateStore.
func (mr *MockGoodsProviderMockRecorder) UpdateStore(ctx, updatedGoods interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStore", reflect.TypeOf((*MockGoodsProvider)(nil).UpdateStore), ctx, updatedGoods)
}
