name: Go CI with Postgres

on:
  push:
    branches: ["db"]
  pull_request:
    branches: ["db"]

jobs:
  test:
    name: Test with Postgres
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_URL: postgres://testuser:testpass@localhost:5432/testdb?sslmode=disable

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.1'  
      - name: Download dependencies
        run: go mod download

      - name: Debug FS
        run: |
          echo "🧠 Current dir: $(pwd)"
          echo "📂 Files:"
          ls -la
          echo "📂 Migrations:"
          ls -la database/migrations

      - name: Run migrations
        run: go run ./database/migrations/migrate.go

      - name: Run integration tests
        run: go test -v ./... -tags=integration
